language: swift
os: osx
osx_image: xcode10

branches:
  only:
  - feature/travis-ci-swift4.2

xcode_project: JSONUtilities.xcodeproj
xcode_scheme: JSONUtilities
xcode_destination: platform=iOS Simulator,OS=12.0,name=iPhone X

