os:
  - osx
language: generic
osx_image: xcode10.1

env:
  global:
  - PROJECT_NAME=JSONUtilities
  matrix:
  - PLATFORM=Mac
  - PLATFORM=iOS NAME='iPhone X'
  - PLATFORM=tvOS NAME='Apple TV 1080p'
  - PLATFORM=watchOS
  - PLATFORM=SPM

script:
  - set -o pipefail;
    case $PLATFORM in
    Mac)
      xcodebuild -scheme $PROJECT_NAME -enableCodeCoverage YES test | xcpretty;;
    iOS)
      xcodebuild -scheme $PROJECT_NAME -destination "name=iPhone X" | xcpretty;;
    tvOS)
      xcodebuild -scheme $PROJECT_NAME -destination "name=Apple TV" | xcpretty;;
    watchOS)
      xcodebuild -scheme $PROJECT_NAME -destination "name=Apple Watch - 38mm" | xcpretty;;
    SPM)
      swift build && swift test;;
    esac

after_success:
  - sleep 5
  - bash <(curl -s https://codecov.io/bash)