language: swift
os: osx
osx_image: xcode10

branches:
  only:
  - feature/travis-ci-swift4.2

xcode_project: JSONUtilities.xcodeproj
xcode_scheme: JSONUtilities

matrix:
  include:
  - name: "iPhone Test"
    swift: "4.2"
    env: PLATFORM=iOS DESTINATION=platform=iOS Simulator,OS=12.0,name=iPhone X

script: 
xcode_destination: $DESTINATION

