os: 
  - osx

language: generic
osx_image: xcode10.0
script:
  - xcodebuild -showsdks
  - xcodebuild -scheme TABSwiftLayout -configuration Debug -sdk iphonesimulator12.0 -destination "OS=12.0,name=iPhone 6s Plus"