language: swift
os: osx
osx_image: xcode10

branches:
  only:
  - feature/travis-ci-swift4.2

xcode_project: JSONUtilities.xcodeproj
xcode_scheme: JSONUtilities

env:
  global: 
  - PROJECT_NAME=JSONUtilities
  matrix:
  - PLATFORM=iOS-iPhoneX SCHEME="JSONUtilities" DESTINATION=platform=iOS Simulator,OS=12.0,name=iPhone X
  - PLATFORM=iOS-iPhone8 SCHEME="JSONUtilities" DESTINATION=platform=iOS Simulator,OS=12.0,name=iPhone 8


script: 
# xcode_destination: $DESTINATION
  - set -o pipefail && xcodebuild -project JSONUtilities.xcodeproj -scheme $SCHEME -destination "platform=iOS Simulator,OS=12.0,name=iPhone X" build-for-testing test | xcpretty


